### ISSUE TITLE
Flatpak runtime is deprecated

### ISSUE THREAD

**Issue by freakboy3742** [beeware/Python-support-testbed#76]
### Describe the bug

As of March 2024, the org.gnome.Platform v44 runtime is deprecated. It should be updated to at least 45.

### Steps to reproduce

Build the Flatpak targets; logs will contain a reference to deprecated Flatpak images

### Expected behavior

Flatpak target should not raise warnings.

### Environment

- Operating System: Linux
- Python version: All
- Software versions:
  - Briefcase: All

### Logs

```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
```

### Additional context

Ordinarily, this should be a simple upgrade; however, the v45 images don't appear to contain `libcrypt.so`. See [this build](
https://github.com/beeware/Python-support-testbed/actions/runs/8872345745/job/24356578771) for an example.

Related issue: beeware/briefcase#1383. Just when we thought this problem had been fixed...

**Comment by freakboy3742** [comment]
Tagging @rmartin16 since you've been tracking these issues. Note the issue with `libcrypt.so` has re-emerged.

**Comment by rmartin16** [comment]
The `_crypt` module still [links](https://gregoryszorc.com/docs/python-build-standalone/main/quirks.html#missing-libcrypt-so-1) `libcrypt.so.1`; indygreg just stopped requiring it loading any of Python. I think that `_crypt` has a hard dependency on this library.

**Comment by freakboy3742** [comment]
Right - It's mostly notable because evidently the v44 runtime *did* have libcrypt; and 45 has removed it (despite it being "required" by LSB". 

I'm guessing the practical fix here is problem to just ignore the test of `crypt`. It's a module that will be removed in Python 3.13; and the test is only being done here to make sure that the module can be loaded. 

It's already ignored on Android and Windows (as it doesn't exist on those platforms). 

Given that nobody *should* be using the module, I don't think it's *that* bad that we don't strictly verify it still works on old versions of Python.

**Comment by rmartin16** [comment]
For posterity, we first hit this with https://github.com/beeware/briefcase/pull/1545.

I didn't realize this repo depends on a Briefcase `pyproject.toml`.....we'll probably benefit from a more exhaustive process to update these across BeeWare....Toga's testbed comes to mind as well.
